import assert from 'node:assert/strict';
import fs from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || new URL('../.test-cache/climate-browser/node_modules/playwright-core/index.mjs',import.meta.url));
const base=process.argv[2]||'http://127.0.0.1:4173/';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/home/users/kieran/.cache/ms-playwright/chromium_headless_shell-1187/chrome-linux/headless_shell',headless:true,ignoreDefaultArgs:['--disable-dev-shm-usage'],args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
 page.setDefaultTimeout(15000);
 page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});
 page.on('crash',()=>console.log('BROWSER PAGE CRASHED'));
 await page.goto(base+'?tab=climate-change');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateScope')?.textContent.includes('models'));
 const view=v=>page.locator(`[data-climate-view-button="${v}"]`).click();
 await view('relationships');
 await page.waitForFunction(()=>document.querySelectorAll('#mlaClimateScatterData tbody tr').length===5);
 await page.selectOption('#mlaClimateScatterX','mean_translation_speed_kmh');
 await page.selectOption('#mlaClimateScatterY','mean_rh500_pct');
 await page.locator('[data-climate-focus="MIROC6"]').first().click();
 await page.$eval('#mlaClimateExploreControls',e=>e.open=true);
 await page.selectOption('#mlaClimateRegion','odisha');
 await page.click('#mlaClimateApplySubset');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateSubsetStatus').textContent.includes('historical → future events'));
 const shared=page.url();await page.evaluate(()=>localStorage.clear());await page.goto(shared);
 await page.waitForFunction(()=>document.querySelector('#mlaClimateSubsetStatus').textContent.includes('historical → future events'));
 assert.equal(await page.inputValue('#mlaClimateRegion'),'odisha');
 assert.equal(await page.inputValue('#mlaClimateScatterX'),'mean_translation_speed_kmh');
 console.log('PASS shared subset URL');
 await view('tracks');
 await page.click('[data-climate-map-action="in"]');
 await page.waitForFunction(()=>new URL(location.href).searchParams.has('cmmapbounds'));
 await page.click('[data-climate-map-action="reset"]');
 await page.click('[data-climate-map-action="box"]');
 const canvas=page.locator('#mlaClimateChangeMap');await canvas.scrollIntoViewIfNeeded();
 const box=await canvas.boundingBox();
 const position=(lon,lat)=>({x:box.x+38+(lon-50)/60*(box.width-48),y:box.y+10+(40-lat)/45*(box.height-44)});
 const a=position(75,15),b=position(87,25);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:5});await page.mouse.up();
 await page.waitForFunction(()=>document.querySelector('#mlaClimateRegion').value==='box'&&!document.querySelector('#mlaClimateApplySubset').disabled);
 console.log('PASS zoom and drawn box');
 await view('rainfall');
 await page.selectOption('#mlaClimateRainRegion','east');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateRainfallCard h3').textContent.includes('East'));
 const downloadPromise=page.waitForEvent('download');await page.click('#mlaClimateDownloadCsv');const download=await downloadPromise;
 assert.match(fs.readFileSync(await download.path(),'utf8'),/rain_region/);
 console.log('PASS regional rainfall and download');
 await page.$eval('#mlaClimateExploreControls',e=>e.open=true);await page.click('#mlaClimateResetSubset');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateRegion').value==='all');
 await page.selectOption('#mlaClimateRegion','box');
 for(const [key,value] of Object.entries({West:'50',South:'-4',East:'52',North:'-2'}))await page.fill('#mlaClimateBox'+key,value);
 await page.click('#mlaClimateApplySubset');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateSubsetStatus').textContent.includes('0 → 0')&&!document.querySelector('#mlaClimateApplySubset').disabled);
 await view('overview');await page.waitForFunction(()=>document.querySelector('#mlaClimateStats').textContent.includes('0.0'));
 await page.click('#mlaClimateResetSubset');
 await page.waitForFunction(()=>document.querySelector('#mlaClimateRegion').value==='all');
 await page.$$eval('#mlaClimateModels input',els=>els.forEach(e=>e.checked=['MIROC6','MPI-ESM1-2-HR'].includes(e.value)));
 await page.click('#mlaClimateApplySubset');await page.waitForFunction(()=>document.querySelector('#mlaClimateScope').textContent.startsWith('2 models'));
 console.log('PASS empty subset and model selection');
 await page.setViewportSize({width:390,height:844});await page.$eval('#mlaClimateExploreControls',e=>e.open=false);await view('relationships');
 await page.locator('#mlaClimateScatterCard').scrollIntoViewIfNeeded();await page.waitForTimeout(300);
 await page.screenshot({path:'.test-cache/era5-browser/climate-new-mobile.png'});
 assert.equal(errors.length,0);console.log('PASS mobile and zero page errors');
}finally{await browser.close();}
