import assert from 'node:assert/strict';
import fs from 'node:fs';
import {gunzipSync} from 'node:zlib';
const {chromium}=await import(new URL('../.test-cache/climate-browser/node_modules/playwright-core/index.mjs',import.meta.url));
const base=process.argv[2]||'http://127.0.0.1:4173/';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const config=JSON.parse(html.match(/<script id="mla-data-config"[^>]*>(.*?)<\/script>/s)[1]);
const core=JSON.parse(gunzipSync(fs.readFileSync(new URL('../'+config.core,import.meta.url))));
const decode=encoded=>{
 let cursor=0,lat=0,lon=0;const points=[];
 const delta=()=>{let n=0,shift=0,byte;do{byte=encoded.charCodeAt(cursor++)-63;n|=(byte&31)<<shift;shift+=5;}while(byte>=32);return n&1?~(n>>1):n>>1;};
 while(cursor<encoded.length){lat+=delta();lon+=delta();points.push([lat/10000,lon/10000]);}return points;
};
const paths=core.paths.map(decode);
// Independent edge-intersection reference, not the application's clipping helper.
const passes=(points,box,breaks)=>{
 const [w,s,e,n]=box, gaps=new Set((breaks||[]).map(x=>x[0]));
 const inside=([lat,lon])=>lat>=s&&lat<=n&&lon>=w&&lon<=e;
 return points.some((p,i)=>{
  if(inside(p))return true;if(!i||gaps.has(i))return false;
  const a=points[i-1],d=[p[0]-a[0],p[1]-a[1]];
  for(const [axis,edge,min,max] of [[0,s,w,e],[0,n,w,e],[1,w,s,n],[1,e,s,n]]){
   if(!d[axis])continue;const t=(edge-a[axis])/d[axis],cross=a[1-axis]+t*d[1-axis];
   if(t>=0&&t<=1&&cross>=min&&cross<=max)return true;
  }return false;
 });
};
const expected=box=>paths.reduce((n,p,i)=>n+Number(passes(p,box,core.breaks?.[i])),0);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/home/users/kieran/.cache/ms-playwright/chromium_headless_shell-1187/chrome-linux/headless_shell',ignoreDefaultArgs:['--disable-dev-shm-usage'],args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>document.querySelector('[data-ready="true"]'));
 const count=async()=>Number((await page.locator('#mlaResultCount').innerText()).split(' of ')[0].replaceAll(',',''));
 const selection=()=>new URL(page.url()).searchParams.get('box')?.split(',').map(Number);
 await page.goto(base);await ready();assert.equal(await count(),core.tracks.length);
 await page.click('#mlaSelectRegion');
 const canvas=page.locator('#mlaMapOverlay');await canvas.scrollIntoViewIfNeeded();
 const rectangle=await canvas.boundingBox();
 const bounds=[Math.floor(core.meta.lon_min)-2,Math.floor(core.meta.lat_min)-2,Math.ceil(core.meta.lon_max)+2,Math.ceil(core.meta.lat_max)+2];
 const scale=Math.min((rectangle.width-48)/(bounds[2]-bounds[0]),(rectangle.height-48)/(bounds[3]-bounds[1]));
 const point=(lon,lat)=>({x:rectangle.x+rectangle.width/2+(lon-(bounds[0]+bounds[2])/2)*scale,y:rectangle.y+rectangle.height/2-(lat-(bounds[1]+bounds[3])/2)*scale});
 const a=point(73,28),b=point(87,18);
 await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:10});await page.mouse.up();
 await page.waitForFunction(()=>new URL(location.href).searchParams.has('box'));
 assert.ok(selection().every((v,i)=>Math.abs(v-[73,18,87,28][i])<.02));
 assert.equal(await count(),expected(selection()));
 assert.equal(await page.locator('#mlaSelectRegion').getAttribute('aria-pressed'),'false');
 assert.equal(await page.locator('#mlaClearRegion').isVisible(),true);
 assert.equal(new URL(page.url()).searchParams.has('system'),false);
 assert.equal(await page.inputValue('#mlaWeatherLayer'),'none');
 assert.match(await page.locator('#mlaActiveFilters').innerText(),/Passes box/);
 const shared=page.url(),selectedCount=await count();
 await canvas.screenshot({path:'.test-cache/era5-browser/explore-box-desktop.png'});
 const pending=page.waitForEvent('download');await page.click('#mlaQuickExport');const download=await pending;
 assert.equal(fs.readFileSync(await download.path(),'utf8').trim().split('\n').length-1,selectedCount);
 const queryPending=page.waitForEvent('download');await page.evaluate(()=>document.querySelector('#mlaDownloadQuery').click());
 const query=JSON.parse(fs.readFileSync(await (await queryPending).path(),'utf8'));
 const queryBox=query.filters.track_passes_box;
 assert.deepEqual([queryBox.west,queryBox.south,queryBox.east,queryBox.north],selection());
 assert.equal(query.matching_physical_event_ids.length,selectedCount);
 console.log('PASS drawn box, independent track geometry, count and CSV export');
 await page.evaluate(()=>localStorage.clear());await page.goto(shared);await ready();assert.equal(await count(),selectedCount);
 await page.click('#mlaClearRegion');assert.equal(await count(),core.tracks.length);assert.equal(selection(),undefined);
 await page.goto(shared+'&class=2,3');await ready();assert.ok(await count()<selectedCount);
 await page.click('#mlaClearRegion');assert.equal(new URL(page.url()).searchParams.get('class'),'2,3');
 assert.equal(await count(),core.tracks.filter(row=>[2,3].includes(row[core.track_fields.indexOf('category')])).length);
 await page.goto(base+'?box=90,30,70,10');await ready();assert.equal(await count(),core.tracks.length);assert.equal(await page.locator('#mlaClearRegion').isVisible(),false);
 await page.goto(base+'?box=-100,-40,-90,-30');await ready();assert.equal(await count(),0);
 await page.click('#mlaClearRegion');assert.equal(await count(),core.tracks.length);
 console.log('PASS shared URL, invalid and empty boxes, clear preserves other filters');
 await page.click('#mlaSelectRegion');await canvas.press('Escape');assert.equal(await page.locator('#mlaSelectRegion').getAttribute('aria-pressed'),'false');
 await page.click('#mlaSelectRegion');await canvas.click({position:{x:100,y:100}});assert.equal(selection(),undefined);assert.equal(new URL(page.url()).searchParams.has('system'),false);
 await canvas.press('Escape');await page.click('#mlaSelectRegion');await canvas.press('Enter');await canvas.press('Shift+ArrowRight');await canvas.press('Shift+ArrowDown');await canvas.press('Enter');
 assert.ok(selection());assert.equal(await count(),expected(selection()));
 await page.click('#mlaResetFilters');assert.equal(selection(),undefined);assert.equal(await count(),core.tracks.length);
 await page.click('#mlaZoomIn');await page.click('#mlaZoomIn');await canvas.scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>new URL(location.href).searchParams.has('centre'));
 const pan=await canvas.boundingBox(),beforePan=new URL(page.url()).searchParams.get('centre');
 await page.mouse.move(pan.x+pan.width/2,pan.y+pan.height/2);await page.mouse.down();await page.mouse.move(pan.x+pan.width/2-50,pan.y+pan.height/2+20,{steps:5});await page.mouse.up();
 await page.waitForFunction(before=>new URL(location.href).searchParams.get('centre')!==before,beforePan);
 assert.notEqual(new URL(page.url()).searchParams.get('centre'),beforePan,'normal map panning still works after box selection');
 console.log('PASS Escape, small-click protection, keyboard selection and reset filters');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto(base);await mobile.waitForFunction(()=>document.querySelector('[data-ready="true"]'));
 await mobile.click('#mlaSelectRegion');const mobileCanvas=mobile.locator('#mlaMapOverlay');await mobileCanvas.scrollIntoViewIfNeeded();
 const r=await mobileCanvas.boundingBox(),cdp=await mobile.context().newCDPSession(mobile);
 const start={x:r.x+r.width*.3,y:r.y+r.height*.4},end={x:r.x+r.width*.65,y:r.y+r.height*.6};
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});
 for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await mobile.waitForFunction(()=>new URL(location.href).searchParams.has('box'));
 assert.equal(await mobile.locator('#mlaSelectRegion').getAttribute('aria-pressed'),'false');
 assert.equal(Number((await mobile.locator('#mlaResultCount').innerText()).split(' of ')[0].replaceAll(',','')),expected(new URL(mobile.url()).searchParams.get('box').split(',').map(Number)));
 await mobileCanvas.screenshot({path:'.test-cache/era5-browser/explore-box-mobile.png'});
 const nav=mobile.locator('[role="group"][aria-label="Map view controls"]');
 assert.equal(await nav.evaluate(el=>new Set([...el.children].map(button=>Math.round(button.getBoundingClientRect().top))).size),1,'map navigation buttons remain on one row');
 await mobile.locator('#mlaSelectRegion').scrollIntoViewIfNeeded();await mobile.screenshot({path:'.test-cache/era5-browser/explore-box-controls-mobile.png'});
 await mobile.click('#mlaClearRegion');assert.equal(new URL(mobile.url()).searchParams.has('box'),false);
 assert.deepEqual(errors,[]);console.log('PASS mobile touch drawing and zero page errors');
}finally{await browser.close();}
