#!/usr/bin/env python3
"""Shared decoding, compact-output and independent QA helpers.

Published tracks are generated by :mod:`forecast_pipeline.v56_tracking`, which
calls the frozen catalogue detector and linker directly.  The small
vorticity/pressure tracker retained here is an independent model-neutral QA
cross-check only; its coordinates are never published.
"""

from __future__ import annotations

import base64
import gzip
import json
import math
import os
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Sequence

import numpy as np
from eccodes import (
    codes_get,
    codes_get_array,
    codes_new_from_message,
    codes_release,
)
from scipy.ndimage import gaussian_filter, maximum_filter, uniform_filter
from scipy.optimize import linear_sum_assignment


EARTH_RADIUS_KM = 6371.0088
DOMAIN = (45.0, -15.0, 120.0, 45.0)  # west, south, east, north
GRID_RESOLUTION = 1.0
GRID_LONS = np.arange(DOMAIN[0], DOMAIN[2] + 0.01, GRID_RESOLUTION, dtype=np.float32)
GRID_LATS = np.arange(DOMAIN[1], DOMAIN[3] + 0.01, GRID_RESOLUTION, dtype=np.float32)


def utc_now() -> datetime:
    return datetime.now(UTC)


def iso_z(value: datetime) -> str:
    return value.astimezone(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


def parse_cycle(value: str) -> datetime:
    return datetime.strptime(value, "%Y%m%d%H").replace(tzinfo=UTC)


def cycle_id(value: datetime) -> str:
    return value.astimezone(UTC).strftime("%Y%m%d%H")


def candidate_cycles(now: datetime | None = None, limit: int = 8) -> list[datetime]:
    """Return recent six-hour cycles, newest first.

    The newest nominal cycle is included; adapters decide whether its requested
    horizon is complete and fall back without confusing source lag with failure.
    """

    value = (now or utc_now()).astimezone(UTC).replace(minute=0, second=0, microsecond=0)
    value -= timedelta(hours=value.hour % 6)
    return [value - timedelta(hours=6 * index) for index in range(limit)]


def haversine_km(first: Sequence[float], second: Sequence[float]) -> float:
    lat1, lon1 = math.radians(float(first[0])), math.radians(float(first[1]))
    lat2, lon2 = math.radians(float(second[0])), math.radians(float(second[1]))
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    value = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return EARTH_RADIUS_KM * 2 * math.atan2(math.sqrt(value), math.sqrt(max(0.0, 1.0 - value)))


@dataclass(frozen=True)
class GridField:
    values: np.ndarray
    short_name: str
    units: str
    step_range: str
    member: str | None


def _normalise_lon(values: np.ndarray) -> np.ndarray:
    return np.mod(values, 360.0)


def decode_grib_message(payload: bytes) -> GridField:
    """Decode one regular latitude/longitude GRIB message onto the 1-degree domain."""

    handle = codes_new_from_message(payload)
    if handle is None:
        raise ValueError("Downloaded byte range does not contain a GRIB message")
    try:
        grid_type = str(codes_get(handle, "gridType"))
        if grid_type not in {"regular_ll", "regular_gg"}:
            raise ValueError(f"Unsupported GRIB grid type {grid_type!r}; regular lat/lon is required")
        ni = int(codes_get(handle, "Ni"))
        nj = int(codes_get(handle, "Nj"))
        latitude = np.asarray(codes_get_array(handle, "latitudes"), dtype=np.float64).reshape(nj, ni)
        longitude = _normalise_lon(np.asarray(codes_get_array(handle, "longitudes"), dtype=np.float64)).reshape(nj, ni)
        values = np.asarray(codes_get_array(handle, "values"), dtype=np.float64).reshape(nj, ni)
        short_name = str(codes_get(handle, "shortName"))
        units = str(codes_get(handle, "units"))
        step_range = str(codes_get(handle, "stepRange"))
        try:
            member = str(codes_get(handle, "perturbationNumber"))
        except Exception:
            member = None
    finally:
        codes_release(handle)

    source_lats = latitude[:, 0]
    source_lons = longitude[0, :]
    if source_lats[0] > source_lats[-1]:
        source_lats = source_lats[::-1]
        values = values[::-1, :]
    lon_order = np.argsort(source_lons)
    source_lons = source_lons[lon_order]
    values = values[:, lon_order]

    lat_index = np.abs(source_lats[:, None] - GRID_LATS[None, :]).argmin(axis=0)
    lon_index = np.abs(source_lons[:, None] - GRID_LONS[None, :]).argmin(axis=0)
    maximum_lat_error = float(np.max(np.abs(source_lats[lat_index] - GRID_LATS)))
    maximum_lon_error = float(np.max(np.abs(source_lons[lon_index] - GRID_LONS)))
    if maximum_lat_error > 0.51 or maximum_lon_error > 0.51:
        raise ValueError(
            f"Source grid cannot represent the target domain at 1 degree "
            f"(lat error {maximum_lat_error:.2f}, lon error {maximum_lon_error:.2f})"
        )
    subset = values[np.ix_(lat_index, lon_index)].astype(np.float32)
    return GridField(subset, short_name, units, step_range, member)


def to_mslp_hpa(field: GridField) -> np.ndarray:
    values = np.asarray(field.values, dtype=np.float32)
    median = float(np.nanmedian(values))
    return values / 100.0 if median > 2_000 else values


def to_precip_mm(field: GridField) -> np.ndarray:
    values = np.maximum(np.asarray(field.values, dtype=np.float32), 0.0)
    units = field.units.lower().replace(" ", "")
    # ECMWF total precipitation is metres; NCEP APCP is kg m-2 (numerically mm).
    if units in {"m", "metres", "metre"} or (field.short_name == "tp" and float(np.nanmax(values)) < 5.0):
        return values * 1000.0
    return values


def relative_vorticity_x1e5(u: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Calculate spherical-grid relative vorticity in 10^-5 s^-1."""

    u = np.asarray(u, dtype=np.float64)
    v = np.asarray(v, dtype=np.float64)
    lat_radians = np.deg2rad(GRID_LATS)
    dy = EARTH_RADIUS_KM * 1000.0 * math.radians(GRID_RESOLUTION)
    dx = dy * np.cos(lat_radians)[:, None]
    dv_dlambda = np.gradient(v, axis=1) / dx
    du_dphi = np.gradient(u, axis=0) / dy
    return ((dv_dlambda - du_dphi) * 1.0e5).astype(np.float32)


def local_pressure_deficit(mslp_hpa: np.ndarray) -> np.ndarray:
    smooth = gaussian_filter(np.asarray(mslp_hpa, dtype=np.float32), sigma=0.8, mode="nearest")
    background = uniform_filter(smooth, size=(9, 9), mode="nearest")
    return (background - smooth).astype(np.float32)


@dataclass
class Candidate:
    step: int
    latitude: float
    longitude: float
    vorticity: float
    pressure_deficit: float
    mslp: float
    score: float


def detect_candidates(step: int, mslp_hpa: np.ndarray, vorticity_x1e5: np.ndarray) -> list[Candidate]:
    """Find permissive forecast LPS centres in one six-hour frame."""

    vort = gaussian_filter(np.asarray(vorticity_x1e5, dtype=np.float32), sigma=1.0, mode="nearest")
    deficit = local_pressure_deficit(mslp_hpa)
    score = np.maximum(vort, 0.0) + 1.35 * np.maximum(deficit, 0.0)
    maxima = score == maximum_filter(score, size=5, mode="nearest")
    valid = (
        maxima
        & np.isfinite(score)
        & np.isfinite(mslp_hpa)
        & (vort >= 0.8)
        & ((deficit >= 0.35) | (vort >= 1.8))
        & (score >= 1.65)
    )
    indices = np.argwhere(valid)
    ranked = sorted(indices, key=lambda ij: float(score[tuple(ij)]), reverse=True)
    retained: list[Candidate] = []
    for lat_index, lon_index in ranked:
        item = Candidate(
            step=int(step),
            latitude=float(GRID_LATS[lat_index]),
            longitude=float(GRID_LONS[lon_index]),
            vorticity=float(vort[lat_index, lon_index]),
            pressure_deficit=float(deficit[lat_index, lon_index]),
            mslp=float(mslp_hpa[lat_index, lon_index]),
            score=float(score[lat_index, lon_index]),
        )
        if all(haversine_km((item.latitude, item.longitude), (old.latitude, old.longitude)) >= 275.0 for old in retained):
            retained.append(item)
        if len(retained) >= 20:
            break
    return retained


def _candidate_cost(previous: Candidate, current: Candidate) -> float:
    distance = haversine_km((previous.latitude, previous.longitude), (current.latitude, current.longitude))
    intensity = abs(previous.vorticity - current.vorticity) * 22.0
    pressure = abs(previous.pressure_deficit - current.pressure_deficit) * 18.0
    return distance + intensity + pressure


def link_candidates(frames: dict[int, list[Candidate]], member: str, role: str) -> list[dict[str, Any]]:
    """Associate frame candidates into conservative six-hour forecast tracks."""

    tracks: list[list[Candidate]] = []
    active: list[int] = []
    for step in sorted(frames):
        candidates = frames[step]
        eligible = [
            index for index in active
            if step - tracks[index][-1].step <= 12
        ]
        assigned_tracks: set[int] = set()
        assigned_candidates: set[int] = set()
        if eligible and candidates:
            matrix = np.full((len(eligible), len(candidates)), 1.0e9, dtype=np.float64)
            for row, track_index in enumerate(eligible):
                previous = tracks[track_index][-1]
                gap = max(6, step - previous.step)
                maximum_distance = 460.0 * gap / 6.0
                for column, current in enumerate(candidates):
                    distance = haversine_km(
                        (previous.latitude, previous.longitude),
                        (current.latitude, current.longitude),
                    )
                    if distance <= maximum_distance:
                        matrix[row, column] = _candidate_cost(previous, current) + max(0, gap - 6) * 20.0
            rows, columns = linear_sum_assignment(matrix)
            for row, column in zip(rows, columns):
                if matrix[row, column] >= 1.0e8:
                    continue
                track_index = eligible[int(row)]
                tracks[track_index].append(candidates[int(column)])
                assigned_tracks.add(track_index)
                assigned_candidates.add(int(column))
        for column, candidate in enumerate(candidates):
            if column not in assigned_candidates:
                tracks.append([candidate])
                assigned_tracks.add(len(tracks) - 1)
        active = [index for index in active if step - tracks[index][-1].step <= 12]
        active.extend(index for index in assigned_tracks if index not in active)

    output: list[dict[str, Any]] = []
    for points in tracks:
        strong = sum(point.vorticity >= 1.4 or point.pressure_deficit >= 0.7 for point in points)
        duration = points[-1].step - points[0].step if points else 0
        if len(points) < 4 or duration < 18 or strong < 2:
            continue
        # Require some relevance to the broad North Indian Ocean / South Asian
        # LPS corridor, but deliberately impose no genesis-basin rule.
        relevant = any(50.0 <= point.longitude <= 112.0 and -5.0 <= point.latitude <= 38.0 for point in points)
        if not relevant:
            continue
        output.append({
            "member": member,
            "role": role,
            "points": [
                [
                    point.step,
                    round(point.longitude, 3),
                    round(point.latitude, 3),
                    round(point.vorticity, 2),
                    round(point.pressure_deficit, 2),
                    round(point.mslp, 1),
                ]
                for point in points
            ],
            "start_step": points[0].step,
            "end_step": points[-1].step,
            "max_vorticity": round(max(point.vorticity for point in points), 2),
            "max_pressure_deficit": round(max(point.pressure_deficit for point in points), 2),
            "minimum_mslp": round(min(point.mslp for point in points), 1),
        })
    output.sort(key=lambda item: (-len(item["points"]), -item["max_vorticity"], item["start_step"]))
    for number, item in enumerate(output, 1):
        item["id"] = f"{member}-T{number:02d}"
    return output


def _track_overlap(first: dict[str, Any], second: dict[str, Any]) -> tuple[int, float]:
    first_points = {int(point[0]): point for point in first["points"]}
    second_points = {int(point[0]): point for point in second["points"]}
    common = sorted(set(first_points) & set(second_points))
    if not common:
        return 0, math.inf
    distances = [
        haversine_km(
            (first_points[step][2], first_points[step][1]),
            (second_points[step][2], second_points[step][1]),
        )
        for step in common
    ]
    return len(common), float(np.median(distances))


def assign_systems(tracks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Cluster member tracks into map-selectable forecast systems."""

    count = len(tracks)
    parent = list(range(count))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(first: int, second: int) -> None:
        root_a, root_b = find(first), find(second)
        if root_a != root_b:
            parent[root_b] = root_a

    for first in range(count):
        for second in range(first + 1, count):
            if tracks[first]["member"] == tracks[second]["member"]:
                continue
            overlap, median = _track_overlap(tracks[first], tracks[second])
            if overlap >= 3 and median <= 425.0:
                union(first, second)

    groups: dict[int, list[int]] = {}
    for index in range(count):
        groups.setdefault(find(index), []).append(index)
    ranked = sorted(
        groups.values(),
        key=lambda indexes: (
            -len({tracks[index]["member"] for index in indexes}),
            min(tracks[index]["start_step"] for index in indexes),
            -max(tracks[index]["max_vorticity"] for index in indexes),
        ),
    )
    systems: list[dict[str, Any]] = []
    for system_number, indexes in enumerate(ranked, 1):
        system_id = f"S{system_number:02d}"
        members = sorted({tracks[index]["member"] for index in indexes})
        for index in indexes:
            tracks[index]["system_id"] = system_id
        all_points = [point for index in indexes for point in tracks[index]["points"]]
        systems.append({
            "id": system_id,
            "label": f"Forecast system {system_number}",
            "track_ids": [tracks[index]["id"] for index in indexes],
            "members": members,
            "member_count": len(members),
            "start_step": min(point[0] for point in all_points),
            "end_step": max(point[0] for point in all_points),
            "mean_start_longitude": round(float(np.mean([point[1] for point in all_points if point[0] == min(p[0] for p in all_points)])), 2),
            "mean_start_latitude": round(float(np.mean([point[2] for point in all_points if point[0] == min(p[0] for p in all_points)])), 2),
        })
    return systems


def quantise_field(values: np.ndarray, scale: float, maximum: float) -> dict[str, Any]:
    source = np.nan_to_num(np.asarray(values, dtype=np.float32), nan=0.0, posinf=maximum, neginf=0.0)
    clipped = np.clip(source, 0.0, maximum)
    encoded = np.rint(clipped / scale).astype(np.uint8)
    compressed = gzip.compress(encoded.tobytes(order="C"), compresslevel=9, mtime=0)
    return {
        "encoding": "gzip-base64-u8",
        "scale": scale,
        "offset": 0.0,
        "shape": list(encoded.shape),
        "data": base64.b64encode(compressed).decode("ascii"),
    }


def compact_weather(vorticity: np.ndarray, precipitation: np.ndarray, basis: str) -> dict[str, Any]:
    return {
        "basis": basis,
        "vorticity": {
            "label": "Positive 850-hPa relative vorticity",
            "units": "10^-5 s^-1",
            **quantise_field(np.maximum(vorticity, 0.0), scale=0.125, maximum=31.875),
        },
        "precipitation": {
            "label": "Trailing 24 h precipitation",
            "units": "mm",
            **quantise_field(np.maximum(precipitation, 0.0), scale=0.5, maximum=127.5),
        },
    }


def trailing_24h(cumulative: np.ndarray, steps: Sequence[int]) -> np.ndarray:
    values = np.asarray(cumulative, dtype=np.float32)
    output = np.zeros_like(values)
    lookup = {int(step): index for index, step in enumerate(steps)}
    for index, step in enumerate(steps):
        previous = lookup.get(int(step) - 24)
        if previous is None:
            output[index] = values[index]
        else:
            output[index] = np.maximum(values[index] - values[previous], 0.0)
    return output


def atomic_write_json_gz(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.parent.chmod(path.parent.stat().st_mode | 0o055)
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(compressed)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.parent.chmod(path.parent.stat().st_mode | 0o055)
    raw = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False).encode("utf-8") + b"\n"
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(raw)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def grid_metadata() -> dict[str, Any]:
    return {
        "west": DOMAIN[0],
        "south": DOMAIN[1],
        "east": DOMAIN[2],
        "north": DOMAIN[3],
        "resolution_degrees": GRID_RESOLUTION,
        "longitude_count": int(GRID_LONS.size),
        "latitude_count": int(GRID_LATS.size),
        "scan": "time, south-to-north, west-to-east",
    }


def validate_cycle_payload(payload: dict[str, Any]) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    steps = [int(value) for value in payload.get("steps", [])]
    if not steps or steps != sorted(set(steps)):
        errors.append("steps must be a non-empty, strictly increasing set")
    if any(step % 6 for step in steps):
        errors.append("all published steps must be six-hourly")
    members = payload.get("members", {})
    available = int(members.get("available", 0))
    expected = int(members.get("expected", 0))
    if available <= 0 or expected <= 0 or available > expected:
        errors.append("member availability is invalid")
    elif available < expected:
        warnings.append(f"partial ensemble: {available}/{expected} members")
    track_ids = [item.get("id") for item in payload.get("tracks", [])]
    if len(track_ids) != len(set(track_ids)):
        errors.append("forecast track IDs are not unique")
    for track in payload.get("tracks", []):
        track_steps = [int(point[0]) for point in track.get("points", [])]
        if track_steps != sorted(set(track_steps)):
            errors.append(f"{track.get('id')}: point steps are not unique and increasing")
        for point in track.get("points", []):
            if not (DOMAIN[0] <= float(point[1]) <= DOMAIN[2] and DOMAIN[1] <= float(point[2]) <= DOMAIN[3]):
                errors.append(f"{track.get('id')}: point outside published domain")
                break
    weather = payload.get("weather")
    if weather:
        expected_shape = [len(steps), int(GRID_LATS.size), int(GRID_LONS.size)]
        for name in ("vorticity", "precipitation"):
            if weather.get(name, {}).get("shape") != expected_shape:
                errors.append(f"{name} weather shape does not match steps/grid")
    status = "failed" if errors else ("warning" if warnings else "passed")
    return {
        "status": status,
        "checked_utc": iso_z(utc_now()),
        "errors": errors,
        "warnings": warnings,
        "track_count": len(payload.get("tracks", [])),
        "system_count": len(payload.get("systems", [])),
    }
