#!/usr/bin/env python3
"""Shared decoding, compact-output and independent QA helpers.

Published tracks are generated by :mod:`forecast_pipeline.v56_tracking`, which
calls the frozen catalogue detector and linker directly.  The small
vorticity/pressure tracker retained here is an independent model-neutral QA
cross-check only; its coordinates are never published.
"""

from __future__ import annotations

import base64
import gzip
import json
import math
import os
import tempfile
import threading
import time
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Sequence

import numpy as np
from eccodes import (
    codes_get,
    codes_get_array,
    codes_new_from_message,
    codes_release,
)
from scipy.ndimage import gaussian_filter, maximum_filter, uniform_filter
from scipy.optimize import linear_sum_assignment


EARTH_RADIUS_KM = 6371.0088
DOMAIN = (45.0, -15.0, 120.0, 45.0)  # west, south, east, north
GRID_RESOLUTION = 1.0
GRID_LONS = np.arange(DOMAIN[0], DOMAIN[2] + 0.01, GRID_RESOLUTION, dtype=np.float32)
GRID_LATS = np.arange(DOMAIN[1], DOMAIN[3] + 0.01, GRID_RESOLUTION, dtype=np.float32)
MANIFEST_LOCK_NAME = ".manifest-v3-lock"
MANIFEST_LOCK_STALE_SECONDS = 600.0
LATEST_CLIENT_MANIFEST = "latest-manifest.json.gz"
ARCHIVE_CLIENT_MANIFEST = "archive-manifest.json.gz"
RECENT_WINDOW_HOURS = 72
MAX_PUBLISHED_TRACK_SPEED_KMH = 200.0


def manifest_lock_path(root: Path) -> Path:
    """Return the shared atomic-directory lock used by every manifest writer."""

    return root / MANIFEST_LOCK_NAME


class ManifestLock:
    """Cross-host manifest lock based on atomic NFS directory creation.

    JASMIN GWS file locks can remain in ``nlmclnt_wait`` after a process exits.
    Atomic directory creation avoids that kernel/NLM state. A heartbeat keeps
    active locks fresh, while an abandoned directory is recoverable after ten
    minutes.
    """

    def __init__(self, root: Path, *, blocking: bool = True, poll_seconds: float = 0.25):
        self.path = manifest_lock_path(root)
        self.blocking = blocking
        self.poll_seconds = poll_seconds
        self.acquired = False
        self._stop = threading.Event()
        self._heartbeat: threading.Thread | None = None

    def _remove_if_stale(self) -> bool:
        try:
            age = time.time() - self.path.stat().st_mtime
        except FileNotFoundError:
            return True
        if age <= MANIFEST_LOCK_STALE_SECONDS:
            return False
        stale = self.path.with_name(
            f"{self.path.name}.stale-{os.getpid()}-{time.time_ns()}"
        )
        try:
            self.path.rename(stale)
            stale.rmdir()
            return True
        except (FileNotFoundError, FileExistsError, OSError):
            return False

    def _touch_until_released(self) -> None:
        while not self._stop.wait(30.0):
            try:
                os.utime(self.path, None)
            except FileNotFoundError:
                return

    def acquire(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        while True:
            try:
                self.path.mkdir(mode=0o755)
            except FileExistsError as error:
                if self._remove_if_stale():
                    continue
                if not self.blocking:
                    raise BlockingIOError(f"manifest lock is busy: {self.path}") from error
                time.sleep(self.poll_seconds)
                continue
            break
        self.acquired = True
        self._stop.clear()
        self._heartbeat = threading.Thread(
            target=self._touch_until_released,
            name="manifest-lock-heartbeat",
            daemon=True,
        )
        self._heartbeat.start()

    def release(self) -> None:
        if not self.acquired:
            return
        self._stop.set()
        if self._heartbeat is not None:
            self._heartbeat.join(timeout=2.0)
        try:
            self.path.rmdir()
        except FileNotFoundError:
            pass
        self.acquired = False

    def __enter__(self) -> "ManifestLock":
        if not self.acquired:
            self.acquire()
        return self

    def __exit__(self, unused_type: Any, unused_value: Any, unused_traceback: Any) -> None:
        self.release()

    def __del__(self) -> None:
        self.release()


def utc_now() -> datetime:
    return datetime.now(UTC)


def iso_z(value: datetime) -> str:
    return value.astimezone(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


def parse_cycle(value: str) -> datetime:
    return datetime.strptime(value, "%Y%m%d%H").replace(tzinfo=UTC)


def cycle_id(value: datetime) -> str:
    return value.astimezone(UTC).strftime("%Y%m%d%H")


def manifest_entry_horizon_hours(entry: dict[str, Any]) -> int:
    """Return the published lead horizon for a manifest cycle entry."""

    try:
        start = datetime.fromisoformat(str(entry["cycle_utc"]).replace("Z", "+00:00"))
        end = datetime.fromisoformat(str(entry["valid_end_utc"]).replace("Z", "+00:00"))
        return max(0, int(round((end - start).total_seconds() / 3600.0)))
    except (KeyError, TypeError, ValueError):
        return 0


def candidate_cycles(now: datetime | None = None, limit: int = 8) -> list[datetime]:
    """Return recent six-hour cycles, newest first.

    The newest nominal cycle is included; adapters decide whether its requested
    horizon is complete and fall back without confusing source lag with failure.
    """

    value = (now or utc_now()).astimezone(UTC).replace(minute=0, second=0, microsecond=0)
    value -= timedelta(hours=value.hour % 6)
    return [value - timedelta(hours=6 * index) for index in range(limit)]


def haversine_km(first: Sequence[float], second: Sequence[float]) -> float:
    lat1, lon1 = math.radians(float(first[0])), math.radians(float(first[1]))
    lat2, lon2 = math.radians(float(second[0])), math.radians(float(second[1]))
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    value = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return EARTH_RADIUS_KM * 2 * math.atan2(math.sqrt(value), math.sqrt(max(0.0, 1.0 - value)))


@dataclass(frozen=True)
class GridField:
    values: np.ndarray
    short_name: str
    units: str
    step_range: str
    member: str | None


def _normalise_lon(values: np.ndarray) -> np.ndarray:
    return np.mod(values, 360.0)


def decode_grib_messages(payloads: Sequence[bytes]) -> GridField:
    """Decode one or more regular-grid GRIB tiles onto the 1-degree domain.

    Most public forecast feeds provide one message covering the whole atlas
    domain.  The Met Office BADC archive instead splits the globe into eight
    tiles; accepting several messages here lets the source adapter join only
    the two tiles intersecting the atlas without first creating a global file.
    """

    if not payloads:
        raise ValueError("No GRIB messages were supplied")
    subset = np.full((GRID_LATS.size, GRID_LONS.size), np.nan, dtype=np.float32)
    metadata: tuple[str, str, str, str | None] | None = None
    for payload in payloads:
        handle = codes_new_from_message(payload)
        if handle is None:
            raise ValueError("Downloaded byte range does not contain a GRIB message")
        try:
            grid_type = str(codes_get(handle, "gridType"))
            if grid_type not in {"regular_ll", "regular_gg"}:
                raise ValueError(f"Unsupported GRIB grid type {grid_type!r}; regular lat/lon is required")
            ni = int(codes_get(handle, "Ni"))
            nj = int(codes_get(handle, "Nj"))
            latitude = np.asarray(codes_get_array(handle, "latitudes"), dtype=np.float64).reshape(nj, ni)
            longitude = _normalise_lon(np.asarray(codes_get_array(handle, "longitudes"), dtype=np.float64)).reshape(nj, ni)
            values = np.asarray(codes_get_array(handle, "values"), dtype=np.float64).reshape(nj, ni)
            short_name = str(codes_get(handle, "shortName"))
            units = str(codes_get(handle, "units"))
            step_range = str(codes_get(handle, "stepRange"))
            try:
                member = str(codes_get(handle, "perturbationNumber"))
            except Exception:
                member = None
        finally:
            codes_release(handle)

        current_metadata = (short_name, units, step_range, member)
        if metadata is None:
            metadata = current_metadata
        elif (metadata[0], metadata[2], metadata[3]) != (short_name, step_range, member):
            raise ValueError(
                "GRIB tiles disagree on field identity "
                f"({metadata[0]}/{metadata[2]}/{metadata[3]} versus {short_name}/{step_range}/{member})"
            )

        source_lats = latitude[:, 0]
        source_lons = longitude[0, :]
        if source_lats[0] > source_lats[-1]:
            source_lats = source_lats[::-1]
            values = values[::-1, :]
        lon_order = np.argsort(source_lons)
        source_lons = source_lons[lon_order]
        values = values[:, lon_order]

        target_lat_mask = (
            (GRID_LATS >= float(np.min(source_lats)) - 0.51)
            & (GRID_LATS <= float(np.max(source_lats)) + 0.51)
        )
        target_lon_mask = (
            (GRID_LONS >= float(np.min(source_lons)) - 0.51)
            & (GRID_LONS <= float(np.max(source_lons)) + 0.51)
        )
        target_lat_indices = np.flatnonzero(target_lat_mask)
        target_lon_indices = np.flatnonzero(target_lon_mask)
        if not target_lat_indices.size or not target_lon_indices.size:
            continue
        lat_index = np.abs(source_lats[:, None] - GRID_LATS[target_lat_indices][None, :]).argmin(axis=0)
        lon_index = np.abs(source_lons[:, None] - GRID_LONS[target_lon_indices][None, :]).argmin(axis=0)
        maximum_lat_error = float(np.max(np.abs(source_lats[lat_index] - GRID_LATS[target_lat_indices])))
        maximum_lon_error = float(np.max(np.abs(source_lons[lon_index] - GRID_LONS[target_lon_indices])))
        if maximum_lat_error > 0.51 or maximum_lon_error > 0.51:
            raise ValueError(
                f"Source grid cannot represent its part of the target domain at 1 degree "
                f"(lat error {maximum_lat_error:.2f}, lon error {maximum_lon_error:.2f})"
            )
        tile_values = values[np.ix_(lat_index, lon_index)].astype(np.float32)
        subset[np.ix_(target_lat_indices, target_lon_indices)] = tile_values

    if metadata is None or np.isnan(subset).any():
        missing = int(np.isnan(subset).sum())
        raise ValueError(f"GRIB message tiles leave {missing} atlas-grid cells uncovered")
    return GridField(subset, *metadata)


def decode_grib_message(payload: bytes) -> GridField:
    """Decode one regular latitude/longitude GRIB message onto the 1-degree domain."""

    return decode_grib_messages([payload])


def to_mslp_hpa(field: GridField) -> np.ndarray:
    values = np.asarray(field.values, dtype=np.float32)
    median = float(np.nanmedian(values))
    return values / 100.0 if median > 2_000 else values


def to_precip_mm(field: GridField) -> np.ndarray:
    values = np.maximum(np.asarray(field.values, dtype=np.float32), 0.0)
    units = field.units.lower().replace(" ", "")
    # ECMWF total precipitation is metres; NCEP APCP is kg m-2 (numerically mm).
    if units in {"m", "metres", "metre"} or (field.short_name == "tp" and float(np.nanmax(values)) < 5.0):
        return values * 1000.0
    return values


def relative_vorticity_x1e5(u: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Calculate spherical-grid relative vorticity in 10^-5 s^-1."""

    u = np.asarray(u, dtype=np.float64)
    v = np.asarray(v, dtype=np.float64)
    lat_radians = np.deg2rad(GRID_LATS)
    dy = EARTH_RADIUS_KM * 1000.0 * math.radians(GRID_RESOLUTION)
    dx = dy * np.cos(lat_radians)[:, None]
    dv_dlambda = np.gradient(v, axis=1) / dx
    du_dphi = np.gradient(u, axis=0) / dy
    return ((dv_dlambda - du_dphi) * 1.0e5).astype(np.float32)


def local_pressure_deficit(mslp_hpa: np.ndarray) -> np.ndarray:
    smooth = gaussian_filter(np.asarray(mslp_hpa, dtype=np.float32), sigma=0.8, mode="nearest")
    background = uniform_filter(smooth, size=(9, 9), mode="nearest")
    return (background - smooth).astype(np.float32)


@dataclass
class Candidate:
    step: int
    latitude: float
    longitude: float
    vorticity: float
    pressure_deficit: float
    mslp: float
    score: float


def detect_candidates(step: int, mslp_hpa: np.ndarray, vorticity_x1e5: np.ndarray) -> list[Candidate]:
    """Find permissive forecast LPS centres in one six-hour frame."""

    vort = gaussian_filter(np.asarray(vorticity_x1e5, dtype=np.float32), sigma=1.0, mode="nearest")
    deficit = local_pressure_deficit(mslp_hpa)
    score = np.maximum(vort, 0.0) + 1.35 * np.maximum(deficit, 0.0)
    maxima = score == maximum_filter(score, size=5, mode="nearest")
    valid = (
        maxima
        & np.isfinite(score)
        & np.isfinite(mslp_hpa)
        & (vort >= 0.8)
        & ((deficit >= 0.35) | (vort >= 1.8))
        & (score >= 1.65)
    )
    indices = np.argwhere(valid)
    ranked = sorted(indices, key=lambda ij: float(score[tuple(ij)]), reverse=True)
    retained: list[Candidate] = []
    for lat_index, lon_index in ranked:
        item = Candidate(
            step=int(step),
            latitude=float(GRID_LATS[lat_index]),
            longitude=float(GRID_LONS[lon_index]),
            vorticity=float(vort[lat_index, lon_index]),
            pressure_deficit=float(deficit[lat_index, lon_index]),
            mslp=float(mslp_hpa[lat_index, lon_index]),
            score=float(score[lat_index, lon_index]),
        )
        if all(haversine_km((item.latitude, item.longitude), (old.latitude, old.longitude)) >= 275.0 for old in retained):
            retained.append(item)
        if len(retained) >= 20:
            break
    return retained


def _candidate_cost(previous: Candidate, current: Candidate) -> float:
    distance = haversine_km((previous.latitude, previous.longitude), (current.latitude, current.longitude))
    intensity = abs(previous.vorticity - current.vorticity) * 22.0
    pressure = abs(previous.pressure_deficit - current.pressure_deficit) * 18.0
    return distance + intensity + pressure


def link_candidates(frames: dict[int, list[Candidate]], member: str, role: str) -> list[dict[str, Any]]:
    """Associate frame candidates into conservative six-hour forecast tracks."""

    tracks: list[list[Candidate]] = []
    active: list[int] = []
    for step in sorted(frames):
        candidates = frames[step]
        eligible = [
            index for index in active
            if step - tracks[index][-1].step <= 12
        ]
        assigned_tracks: set[int] = set()
        assigned_candidates: set[int] = set()
        if eligible and candidates:
            matrix = np.full((len(eligible), len(candidates)), 1.0e9, dtype=np.float64)
            for row, track_index in enumerate(eligible):
                previous = tracks[track_index][-1]
                gap = max(6, step - previous.step)
                maximum_distance = 460.0 * gap / 6.0
                for column, current in enumerate(candidates):
                    distance = haversine_km(
                        (previous.latitude, previous.longitude),
                        (current.latitude, current.longitude),
                    )
                    if distance <= maximum_distance:
                        matrix[row, column] = _candidate_cost(previous, current) + max(0, gap - 6) * 20.0
            rows, columns = linear_sum_assignment(matrix)
            for row, column in zip(rows, columns):
                if matrix[row, column] >= 1.0e8:
                    continue
                track_index = eligible[int(row)]
                tracks[track_index].append(candidates[int(column)])
                assigned_tracks.add(track_index)
                assigned_candidates.add(int(column))
        for column, candidate in enumerate(candidates):
            if column not in assigned_candidates:
                tracks.append([candidate])
                assigned_tracks.add(len(tracks) - 1)
        active = [index for index in active if step - tracks[index][-1].step <= 12]
        active.extend(index for index in assigned_tracks if index not in active)

    output: list[dict[str, Any]] = []
    for points in tracks:
        strong = sum(point.vorticity >= 1.4 or point.pressure_deficit >= 0.7 for point in points)
        duration = points[-1].step - points[0].step if points else 0
        if len(points) < 4 or duration < 18 or strong < 2:
            continue
        # Require some relevance to the broad North Indian Ocean / South Asian
        # LPS corridor, but deliberately impose no genesis-basin rule.
        relevant = any(50.0 <= point.longitude <= 112.0 and -5.0 <= point.latitude <= 38.0 for point in points)
        if not relevant:
            continue
        output.append({
            "member": member,
            "role": role,
            "points": [
                [
                    point.step,
                    round(point.longitude, 3),
                    round(point.latitude, 3),
                    round(point.vorticity, 2),
                    round(point.pressure_deficit, 2),
                    round(point.mslp, 1),
                ]
                for point in points
            ],
            "start_step": points[0].step,
            "end_step": points[-1].step,
            "max_vorticity": round(max(point.vorticity for point in points), 2),
            "max_pressure_deficit": round(max(point.pressure_deficit for point in points), 2),
            "minimum_mslp": round(min(point.mslp for point in points), 1),
        })
    output.sort(key=lambda item: (-len(item["points"]), -item["max_vorticity"], item["start_step"]))
    for number, item in enumerate(output, 1):
        item["id"] = f"{member}-T{number:02d}"
    return output


def _track_overlap(first: dict[str, Any], second: dict[str, Any]) -> tuple[int, float]:
    first_points = {int(point[0]): point for point in first["points"]}
    second_points = {int(point[0]): point for point in second["points"]}
    common = sorted(set(first_points) & set(second_points))
    if not common:
        return 0, math.inf
    distances = [
        haversine_km(
            (first_points[step][2], first_points[step][1]),
            (second_points[step][2], second_points[step][1]),
        )
        for step in common
    ]
    return len(common), float(np.median(distances))


def assign_systems(tracks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Cluster member tracks into map-selectable forecast systems."""

    count = len(tracks)
    parent = list(range(count))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(first: int, second: int) -> None:
        root_a, root_b = find(first), find(second)
        if root_a != root_b:
            parent[root_b] = root_a

    for first in range(count):
        for second in range(first + 1, count):
            if tracks[first]["member"] == tracks[second]["member"]:
                continue
            overlap, median = _track_overlap(tracks[first], tracks[second])
            if overlap >= 3 and median <= 425.0:
                union(first, second)

    groups: dict[int, list[int]] = {}
    for index in range(count):
        groups.setdefault(find(index), []).append(index)
    ranked = sorted(
        groups.values(),
        key=lambda indexes: (
            -len({tracks[index]["member"] for index in indexes}),
            min(tracks[index]["start_step"] for index in indexes),
            -max(tracks[index]["max_vorticity"] for index in indexes),
        ),
    )
    systems: list[dict[str, Any]] = []
    for system_number, indexes in enumerate(ranked, 1):
        system_id = f"S{system_number:02d}"
        members = sorted({tracks[index]["member"] for index in indexes})
        for index in indexes:
            tracks[index]["system_id"] = system_id
        all_points = [point for index in indexes for point in tracks[index]["points"]]
        systems.append({
            "id": system_id,
            "label": f"Forecast system {system_number}",
            "track_ids": [tracks[index]["id"] for index in indexes],
            "members": members,
            "member_count": len(members),
            "start_step": min(point[0] for point in all_points),
            "end_step": max(point[0] for point in all_points),
            "mean_start_longitude": round(float(np.mean([point[1] for point in all_points if point[0] == min(p[0] for p in all_points)])), 2),
            "mean_start_latitude": round(float(np.mean([point[2] for point in all_points if point[0] == min(p[0] for p in all_points)])), 2),
        })
    return systems


def quantise_field(values: np.ndarray, scale: float, maximum: float) -> dict[str, Any]:
    source = np.nan_to_num(np.asarray(values, dtype=np.float32), nan=0.0, posinf=maximum, neginf=0.0)
    clipped = np.clip(source, 0.0, maximum)
    encoded = np.rint(clipped / scale).astype(np.uint8)
    compressed = gzip.compress(encoded.tobytes(order="C"), compresslevel=9, mtime=0)
    return {
        "encoding": "gzip-base64-u8",
        "scale": scale,
        "offset": 0.0,
        "shape": list(encoded.shape),
        "data": base64.b64encode(compressed).decode("ascii"),
    }


def compact_weather(vorticity: np.ndarray, precipitation: np.ndarray, basis: str) -> dict[str, Any]:
    return {
        "basis": basis,
        "vorticity": {
            "label": "Positive 850-hPa relative vorticity",
            "units": "10^-5 s^-1",
            **quantise_field(np.maximum(vorticity, 0.0), scale=0.125, maximum=31.875),
        },
        "precipitation": {
            "label": "Trailing 24 h precipitation",
            "units": "mm",
            **quantise_field(np.maximum(precipitation, 0.0), scale=0.5, maximum=127.5),
        },
    }


def compact_track_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Return the fast map-first variant of a public forecast payload.

    Weather grids dominate deterministic cycle downloads and are unnecessary
    until somebody requests an overlay or selects a system for its rainfall
    evolution.  The sidecar retains the complete published tracks and a small
    field inventory, while omitting both grids and internal tracker QA.
    """

    output = dict(payload)
    weather = output.pop("weather", {})
    output.pop("tracking_qa", None)
    output["weather_available"] = sorted(
        name
        for name, field in weather.items()
        if isinstance(field, dict) and "shape" in field and "data" in field
    )
    output["payload_variant"] = "tracks"
    return output


def track_sidecar_url(relative_url: str) -> str:
    """Return the stable map-first sidecar name for a compressed payload."""

    suffix = ".json.gz"
    if not str(relative_url).endswith(suffix):
        raise ValueError(f"forecast payload URL must end in {suffix}: {relative_url}")
    return f"{str(relative_url)[:-len(suffix)]}.tracks{suffix}"


def trailing_24h(cumulative: np.ndarray, steps: Sequence[int]) -> np.ndarray:
    values = np.asarray(cumulative, dtype=np.float32)
    output = np.zeros_like(values)
    lookup = {int(step): index for index, step in enumerate(steps)}
    for index, step in enumerate(steps):
        previous = lookup.get(int(step) - 24)
        if previous is None:
            output[index] = values[index]
        else:
            output[index] = np.maximum(values[index] - values[previous], 0.0)
    return output


def atomic_write_json_gz(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.parent.chmod(path.parent.stat().st_mode | 0o055)
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(compressed)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.parent.chmod(path.parent.stat().st_mode | 0o055)
    raw = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False).encode("utf-8") + b"\n"
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(raw)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def publish_client_manifests(root: Path, manifest: dict[str, Any]) -> None:
    """Publish small mode-specific manifests for the static browser client.

    ``manifest.json`` remains the authoritative writer/merge contract.  The
    browser should not download its complete archive inventory merely to open
    current guidance, so Latest and Archive receive independently compressed
    projections of that contract.
    """

    latest_keys = (
        "schema",
        "generated_utc",
        "run_started_utc",
        "schedule",
        "forecast_horizon_hours",
        "forecast_horizons_hours",
        "forecast_horizon_policy",
        "weather_archive_policy",
        "analysis_stitch_policy",
        "catalogue_verification",
        "models",
        "latest",
        "recent",
        "analysis_history",
        "attempts",
        "source_notes",
        "run",
    )
    latest = {key: manifest[key] for key in latest_keys if key in manifest}
    latest["recent"] = client_recent_entries(manifest)
    latest["client_manifest"] = "latest"
    archive = {
        "schema": manifest.get("schema", "mla-forecast-manifest-v1"),
        "generated_utc": manifest.get("generated_utc"),
        "models": manifest.get("models", []),
        "archive": manifest.get("archive", []),
        "tigge_archive": manifest.get("tigge_archive", []),
        "client_manifest": "archive",
    }
    for key in ("archive_horizons_hours", "tigge_archive_horizons_hours"):
        if key in manifest:
            archive[key] = manifest[key]
    atomic_write_json_gz(root / LATEST_CLIENT_MANIFEST, latest)
    atomic_write_json_gz(root / ARCHIVE_CLIENT_MANIFEST, archive)


def client_recent_entries(
    manifest: dict[str, Any],
    window_hours: int = RECENT_WINDOW_HOURS,
) -> dict[str, list[dict[str, Any]]]:
    """Project available operational archive cycles into the Latest window.

    The permanent operational archive already owns the full payload for most
    recent initializations. Reusing those URLs avoids downloading and storing
    a duplicate merely to expose another initialization in Latest. A current
    ``cycles/`` entry wins only when it has a longer published lead axis (or
    ties), while TIGGE remains archive-only.
    """

    archive_by_model: dict[str, list[dict[str, Any]]] = {}
    for entry in manifest.get("archive", []):
        model = str(entry.get("model", ""))
        if model:
            archive_by_model.setdefault(model, []).append(entry)
    output: dict[str, list[dict[str, Any]]] = {}
    for model, latest_entry in manifest.get("latest", {}).items():
        try:
            newest = datetime.fromisoformat(
                str(latest_entry["cycle_utc"]).replace("Z", "+00:00")
            )
        except (KeyError, TypeError, ValueError):
            output[model] = list(manifest.get("recent", {}).get(model, []))
            continue
        oldest = newest - timedelta(hours=window_hours)
        selected: dict[str, tuple[tuple[int, int, int], dict[str, Any]]] = {}
        sources = (
            (0, archive_by_model.get(model, [])),
            (1, manifest.get("recent", {}).get(model, [])),
            (2, [latest_entry]),
        )
        for source_priority, entries in sources:
            for entry in entries:
                try:
                    cycle_time = datetime.fromisoformat(
                        str(entry["cycle_utc"]).replace("Z", "+00:00")
                    )
                    cycle = str(entry["cycle"])
                except (KeyError, TypeError, ValueError):
                    continue
                if cycle_time < oldest or cycle_time > newest:
                    continue
                score = (
                    manifest_entry_horizon_hours(entry),
                    len(entry.get("weather_fields", [])),
                    source_priority,
                )
                if cycle not in selected or score > selected[cycle][0]:
                    selected[cycle] = (score, entry)
        output[model] = [
            value[1]
            for _, value in sorted(selected.items(), reverse=True)
        ]
    return output


def grid_metadata() -> dict[str, Any]:
    return {
        "west": DOMAIN[0],
        "south": DOMAIN[1],
        "east": DOMAIN[2],
        "north": DOMAIN[3],
        "resolution_degrees": GRID_RESOLUTION,
        "longitude_count": int(GRID_LONS.size),
        "latitude_count": int(GRID_LATS.size),
        "scan": "time, south-to-north, west-to-east",
    }


def validate_cycle_payload(payload: dict[str, Any]) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    steps = [int(value) for value in payload.get("steps", [])]
    if not steps or steps != sorted(set(steps)):
        errors.append("steps must be a non-empty, strictly increasing set")
    if any(step % 6 for step in steps):
        errors.append("all published steps must be six-hourly")
    members = payload.get("members", {})
    available = int(members.get("available", 0))
    expected = int(members.get("expected", 0))
    if available <= 0 or expected <= 0 or available > expected:
        errors.append("member availability is invalid")
    elif available < expected:
        warnings.append(f"partial ensemble: {available}/{expected} members")
    track_ids = [item.get("id") for item in payload.get("tracks", [])]
    if len(track_ids) != len(set(track_ids)):
        errors.append("forecast track IDs are not unique")
    for track in payload.get("tracks", []):
        track_points = track.get("points", [])
        track_steps = [int(point[0]) for point in track_points]
        if track_steps != sorted(set(track_steps)):
            errors.append(f"{track.get('id')}: point steps are not unique and increasing")
        for point in track_points:
            if not (DOMAIN[0] <= float(point[1]) <= DOMAIN[2] and DOMAIN[1] <= float(point[2]) <= DOMAIN[3]):
                errors.append(f"{track.get('id')}: point outside published domain")
                break
        for previous, current in zip(track_points, track_points[1:]):
            elapsed = int(current[0]) - int(previous[0])
            if elapsed <= 0:
                continue
            speed = haversine_km(
                (float(previous[2]), float(previous[1])),
                (float(current[2]), float(current[1])),
            ) / elapsed
            if speed > MAX_PUBLISHED_TRACK_SPEED_KMH:
                errors.append(
                    f"{track.get('id')}: implausible {speed:.1f} km h-1 jump "
                    f"between +{int(previous[0])} and +{int(current[0])} h"
                )
                break
    weather = payload.get("weather")
    if weather:
        expected_shape = [len(steps), int(GRID_LATS.size), int(GRID_LONS.size)]
        for name in ("vorticity", "precipitation"):
            if weather.get(name, {}).get("shape") != expected_shape:
                errors.append(f"{name} weather shape does not match steps/grid")
    status = "failed" if errors else ("warning" if warnings else "passed")
    return {
        "status": status,
        "checked_utc": iso_z(utc_now()),
        "errors": errors,
        "warnings": warnings,
        "track_count": len(payload.get("tracks", [])),
        "system_count": len(payload.get("systems", [])),
    }
